In [ ]:
#importando a base utilizada no projeto
#https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")
print(df)

Saving Sleep_health_and_lifestyle_dataset.csv to Sleep_health_and_lifestyle_dataset.csv
     Person ID  Gender  Age            Occupation  Sleep Duration  \
0            1    Male   27     Software Engineer             6.1   
1            2    Male   28                Doctor             6.2   
2            3    Male   28                Doctor             6.2   
3            4    Male   28  Sales Representative             5.9   
4            5    Male   28  Sales Representative             5.9   
..         ...     ...  ...                   ...             ...   
369        370  Female   59                 Nurse             8.1   
370        371  Female   59                 Nurse             8.0   
371        372  Female   59                 Nurse             8.1   
372        373  Female   59                 Nurse             8.1   
373        374  Female   59                 Nurse             8.1   

     Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0     

In [ ]:
#Tratamento dos dados para ser utilizado no Método de IA escolhido

df = df.drop(["Daily Steps", "Person ID", "Occupation", "Heart Rate", "Gender"], axis = 1)
df = df.replace("Normal Weight", "Normal")
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df["BMI Category"] = le.fit_transform(df["BMI Category"])
df['Sleep Disorder'] = le.fit_transform(df['Sleep Disorder'])
new = df['Blood Pressure'].str.split("/", n =1, expand = True)
media = []
for i in range(0, 374):
  media.append((int(new[0][i]) + int(new[1][i]))/2)
df["BloodPressure"] = media
df.drop(["Blood Pressure"], axis = 1, inplace= True)
x = df[["Sleep Duration", "Physical Activity Level", "Stress Level", "BMI Category", 'Sleep Disorder', 'BloodPressure']]
y = df["Quality of Sleep"]


In [ ]:
#Utilização do Método de IA escolhido
#Método KNN
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6, metric='euclidean')
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)


In [ ]:
# Retorna a matriz de confusão mostrando os acertos e erros da nossa previsão
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import classification_report
print('\n',classification_report(y_test, y_pred))

[[ 0  3  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0 40  1  0  0]
 [ 0  1  5 21  3  1]
 [ 0  0  3  1 45  0]
 [ 0  0  1  0  1 21]]

               precision    recall  f1-score   support

           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         3
           6       0.77      0.98      0.86        41
           7       0.91      0.68      0.78        31
           8       0.92      0.92      0.92        49
           9       0.95      0.91      0.93        23

    accuracy                           0.85       150
   macro avg       0.59      0.58      0.58       150
weighted avg       0.85      0.85      0.84       150



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
